site_name: TikZJax
site_description: Documentation de TikZJax
site_url: https://rod2ik.github.io/tikzjax/
repo_url: https://github.com/rod2ik/tikzjax
repo_name: rod2ik/tikzjax

theme:
  name: material
  custom_dir: overrides
  language: fr
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:                        # Palettes de couleurs jour/nuit
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: blue
        accent: blue
        toggle:
            icon: material/weather-night
            name: Passer au mode nuit
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: pink
        accent: pink
        toggle:
            icon: material/weather-sunny
            name: Passer au mode jour

nav:
  - Home: index.md
  - Installation:
      - Start Page: installation/index.md
      - On Custom Standalone HTML: 
        - Installation: installation/html.md
        - Minimal Standalone HTML Page: installation/minimal.html
        - Advanced Standalone HTML Page: installation/advanced.html
      - On an MkDocs Site: installation/mkdocs.md
  - Usage:
      - Basic Examples: basic-examples.md
      - Advanced Examples: advanced-examples.md
  - Configuration:
      - Overview: configuration.md
      - Light/Dark themes: themes.md
      - Fallback Error Images: fallback-error-images.md
  - Advanced:
      - Cache and Performance: cache-performance.md
      - API Reference: api-reference.md
      - Architecture: architecture.md
      - Troubleshooting: troubleshooting.md
  - DEBUG:
      - Page1: debug/page1.md
      - Page2: debug/page2.md

plugins:
  - search

hooks:
  - postprocess_tikzjax_version.py

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.arithmatex:
      generic: true
      smart_dollar: false
  - pymdownx.superfences:   # for ```tikzjax ... ``` syntaxes
      custom_fences:
        - name: tikzjax
          class: language-tikzjax
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - assets/css/style.css
  - assets/css/columns.css
  - assets/css/dynabadges.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@4.1.0/tex-mml-chtml.js
  - assets/javascripts/tikzjax.config.js
  - assets/javascripts/dynabadges.config.js
